name: tiny-erlang

default-extensions:
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - FlexibleInstances
  - BlockArguments
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - TypeFamilies

dependencies:
  - base >= 4.14 && < 5
  - text
  - mtl
  - containers
  - megaparsec
  - stm
  - async
  - array # for alex

build-tools:
  - alex

ghc-options:
  - -Wincomplete-patterns

executables:
  tiny-erlang:
    main: Main.hs
    source-dirs: app
